name: Send description

on:
  workflow_dispatch:

jobs:
  build:
    name: Send description
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: 151013160191
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: 151013160191/test-trivy
