name: Build and Push Docker Image to Docker Hub

on:
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: 151013160191
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: docker build -t 151013160191/test-trivy:latest .

    - name: Push Docker image to Docker Hub
      run: docker push 151013160191/test-trivy:latest



